name: structure
description: structure project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  anchored_popups: ^0.1.0
  animate_do: ^2.0.0
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.0+1
  cached_network_image: ^3.0.0
  cloudinary_public: ^0.8.0
  context_menus: ^0.1.0+5
  darq: ^1.0.0-dev.3
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0+3
  email_validator: ^2.0.1
  enum_to_string: ^2.0.1
  flutter_lorem: ^2.0.0
  flextras: ^0.0.1
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_linux: ^0.0.2
  file_selector_web: ^0.8.1
  flutter_svg: ^1.1.6
  image_picker: ^0.8.0+4
  image_size_getter: ^1.0.0
  multi_image_picker: ^4.8.00
  path_provider: ^2.0.1
  provider: ^5.0.0
  random_color: ^1.0.5
  sized_context: ^1.0.0+1
  shared_preferences: ^2.0.4
  share: ^2.0.1
  system_info: ^1.0.0
  statsfl: ^2.0.1+1
  timeago: ^3.0.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  visibility_detector: ^0.2.2

  # FIREBASE
  firedart: ^0.9.0+1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1

dev_dependencies:
  # sample build cmd
  # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^1.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable:
  flutter_launcher_icons: ^0.9.0
  msix: ^3.7.0